export const INTELYCHAT_SET_USER = 'INTELYCHAT_SET_USER';
export const INTELYCHAT_RESET = 'INTELYCHAT_RESET';

export const ANALYTICS_IDENTITY = 'ANALYTICS_IDENTITY';
export const ANALYTICS_RESET = 'ANALYTICS_RESET';
